langchain4j:
  open-ai:
    chat-model:
      base-url: https://api.deepseek.com
      api-key: sk-21d639547596400289c831fab87782eb
      model-name: deepseek-chat
      log-requests: true
      log-responses: true
      max-tokens: 8192
      max-retries: 3
    streaming-chat-model:
      base-url: https://api.deepseek.com
      api-key: sk-21d639547596400289c831fab87782eb
      model-name: deepseek-chat
      log-requests: true
      log-responses: true
      max-tokens: 8192
      max-retries: 3
