spring:
  application:
    name: openchat-backed
  profiles:
    active: local
server:
  port: 8080
  servlet:
    context-path: /api
springdoc:
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.jiang.delineatewordsbacked.aiservice
knife4j:
  enable: true
  setting:
    language: zh_cn
